/*ACCESS TABLES*/
 
CREATE TABLE JINRANY2_A4_DEPARTMENT AS
SELECT *
FROM jguo24.A4_DEPARTMENT;

CREATE TABLE JINRANY2_A4_DEPENDENT AS
SELECT *
FROM jguo24.A4_DEPENDENT;

CREATE TABLE JINRANY2_A4_LOCATIONS AS
SELECT *
FROM JGUO24.A4_DEPT_LOCATIONS;

CREATE TABLE JINRANY2_A4_EMPLOYEE AS
SELECT * 
FROM JGUO24.A4_EMPLOYEE;

CREATE TABLE JINRANY2_A4_PROJECT AS
SELECT * 
FROM JGUO24.A4_PROJECT;

CREATE TABLE JINRANY2_A4_WORKS_ON AS
SELECT * 
FROM JGUO24.A4_WORKS_ON;

--a) Retrieve the names of all employees in Department 5 who work more than 10 hours per week on the ‘Product X’ project.

SELECT FNAME, MINIT, LNAME
FROM JINRANY2_A4_EMPLOYEE JOIN JINRANY2_A4_WORKS_ON
      ON SSN = ESSN
      JOIN JINRANY2_A4_PROJECT
      ON JINRANY2_A4_WORKS_ON.PNO = JINRANY2_A4_PROJECT.PNUMBER
WHERE JINRANY2_A4_PROJECT.PNAME = 'ProductX' AND
      JINRANY2_A4_WORKS_ON.HOURS > 10
      and DNO =5 ;
      
--b) List the names of all employees who have a dependent with the same first name as themselves.

INSERT INTO JINRANY2_A4_DEPENDENT(ESSN, DEPENDENT_NAME, SEX, BDATE, RELATIONSHIP)
VALUES('888665555','James','F'，TO_DATE('12-APR-80'),'son');

SELECT FNAME,MINIT,LNAME
FROM JINRANY2_A4_EMPLOYEE JOIN JINRANY2_A4_DEPENDENT
     ON JINRANY2_A4_EMPLOYEE.SSN = JINRANY2_A4_DEPENDENT.ESSN
WHERE JINRANY2_A4_EMPLOYEE.FNAME = JINRANY2_A4_DEPENDENT.DEPENDENT_NAME;

--c) Find the names of all employees who are directly supervised by ‘Franklin Wong’.

SELECT FNAME,MINIT,LNAME
FROM JINRANY2_A4_EMPLOYEE
WHERE SUPERSSN = (SELECT SSN FROM JINRANY2_A4_EMPLOYEE WHERE FNAME = 'Franklin' AND LNAME = 'Wong');


--d) For each project, list the project name and the total hours per week (by all employees) spent on that project.

SELECT PNAME, SUM(HOURS)
FROM JINRANY2_A4_PROJECT,JINRANY2_A4_WORKS_ON
WHERE JINRANY2_A4_PROJECT.PNUMBER = JINRANY2_A4_WORKS_ON.PNO
GROUP BY PNAME;

--E)For each department,retrieve the department name and the average salary of all employees working in that department.

SELECT DNAME, AVG(JINRANY2_A4_EMPLOYEE.SALARY)
FROM JINRANY2_A4_DEPARTMENT, JINRANY2_A4_EMPLOYEE
WHERE JINRANY2_A4_DEPARTMENT.DNUMBER = JINRANY2_A4_EMPLOYEE.DNO
GROUP BY DNAME;

--F) Retrieve the name of employees who work on EVERY project.

INSERT INTO JINRANY2_A4_WORKS_ON(ESSN, PNO,HOURS)
VALUES('333445555','1','3');
INSERT INTO JINRANY2_A4_WORKS_ON(ESSN, PNO,HOURS)
VALUES('333445555','30','7');
INSERT INTO JINRANY2_A4_WORKS_ON(ESSN, PNO,HOURS)
VALUES('333445555','61','25');
INSERT INTO JINRANY2_A4_WORKS_ON(ESSN, PNO,HOURS)
VALUES('333445555','62','18');
INSERT INTO JINRANY2_A4_WORKS_ON(ESSN, PNO,HOURS)
VALUES('333445555','63','13');
INSERT INTO JINRANY2_A4_WORKS_ON(ESSN, PNO,HOURS)
VALUES('333445555','91','13');
INSERT INTO JINRANY2_A4_WORKS_ON(ESSN, PNO,HOURS)
VALUES('333445555','92','5');

SELECT JINRANY2_A4_EMPLOYEE.FNAME,JINRANY2_A4_EMPLOYEE.MINIT,JINRANY2_A4_EMPLOYEE.LNAME
FROM JINRANY2_A4_EMPLOYEE
WHERE NOT EXISTS
(SELECT JINRANY2_A4_PROJECT.PNUMBER
       FROM JINRANY2_A4_PROJECT
       where NOT EXISTS
       (SELECT *
              FROM JINRANY2_A4_WORKS_ON
              WHERE JINRANY2_A4_EMPLOYEE.SSN = JINRANY2_A4_WORKS_ON.ESSN
              AND JINRANY2_A4_WORKS_ON.PNO = JINRANY2_A4_PROJECT.PNUMBER));
              
--G) Retrieve the average salary of all female employees 
SELECT AVG(SALARY)
FROM JINRANY2_A4_EMPLOYEE
WHERE JINRANY2_A4_EMPLOYEE.SEX = 'F';

--H) Find the names and addresses of all employees who work on at least one project located in Houston, but whose department has no location in Houston.

SELECT FNAME,MINIT,LNAME,ADDRESS
FROM JINRANY2_A4_EMPLOYEE
WHERE EXISTS (
              SELECT *
              FROM JINRANY2_A4_WORKS_ON,JINRANY2_A4_PROJECT
              WHERE JINRANY2_A4_WORKS_ON.ESSN = JINRANY2_A4_EMPLOYEE.SSN
                    AND JINRANY2_A4_WORKS_ON.PNO = JINRANY2_A4_PROJECT.PNUMBER
                    AND JINRANY2_A4_PROJECT.PLOCATION = 'Houston')
    AND NOT EXISTS(
            SELECT *
            FROM JINRANY2_A4_LOCATIONS
            WHERE JINRANY2_A4_EMPLOYEE.DNO = JINRANY2_A4_LOCATIONS.DNUMBER
            AND JINRANY2_A4_LOCATIONS.DLOCATION ='Houston');




--i）List the last names of all department managers who have no dependents.

SELECT JINRANY2_A4_EMPLOYEE.FNAME
FROM JINRANY2_A4_EMPLOYEE
WHERE EXISTS (SELECT *
              FROM JINRANY2_A4_DEPARTMENT
              WHERE JINRANY2_A4_EMPLOYEE.SSN = JINRANY2_A4_DEPARTMENT.MGRSSN)
      AND NOT EXISTS(SELECT *
                     FROM JINRANY2_A4_DEPENDENT
                     WHERE JINRANY2_A4_EMPLOYEE.SSN = JINRANY2_A4_DEPENDENT.ESSN);
                     
                     
grant select on JINRANY2_A4_DEPARTMENT to GSLISDM;
grant select on JINRANY2_A4_DEPENDENT to GSLISDM;
grant select on JINRANY2_A4_DEPT_LOCATIONS to GSLISDM;
grant select on JINRANY2_A4_EMPLOYEE to GSLISDM;
grant select on JINRANY2_A4_PROJECT to GSLISDM;
grant select on JINRANY2_A4_WORKS_ON to GSLISDM;
grant select on JINRANY2_A4_DEPARTMENT to jguo24;
grant select on JINRANY2_A4_DEPENDENT to jguo24;
grant select on JINRANY2_A4_DEPT_LOCATIONS to jguo24;
grant select on JINRANY2_A4_EMPLOYEE to jguo24;
grant select on JINRANY2_A4_PROJECT to jguo24;
grant select on JINRANY2_A4_WORKS_ON to jguo24;